**Programming Assignment 2**

Munsayac, Angela Ysabhelle C.

2ECE-B 

EXPERIMENT 2
NUMERICAL PYTHON (NUMPY) 


In [1]:
import numpy as np

**NORMALIZATION PROBLEM**

In [5]:
import numpy as np                           #import numpy for numerical operations such as ndarray

x = np.random.rand(5, 5)                     #Create random 5x5 array

x_normalized = (x - x.mean()) / x.std()      #formula to get the mean and standard deviation


print("\nNormalized x:\n", x_normalized)     #output and printing the result of the 5X5 array 


Normalized x:
 [[-1.52766284 -1.29583074  0.96586726 -0.52056486 -1.00004436]
 [-1.64290436  1.10387599  1.65370324  0.28168754 -0.31452545]
 [-1.03149607 -0.2035251  -0.7913258   1.11882659  0.14809657]
 [ 1.70999108  0.73902417 -0.75533696  0.08229823 -0.72358897]
 [ 1.53287969 -0.61615127  0.93626555  0.69113955 -0.54069869]]


 **DIVISIBLE BY 3 PROBLEM**
 

In [6]:
import numpy as np

                                                                    # Create array of squares of the first 100 positive integers
a = np.array([(i + 1) ** 2 for i in range(100)]).reshape(10, 10)    # ([(i + 1) ** 2 for i in range(100)]gives squares of 1² to 100². 
                                                                    #.reshape(10, 10) makes it a 10×10 array (same shape as your original).

                                                                    # np.sum(a % 3 == 0) counts elements divisible by 3   
                                                                    # Count how many are divisible by 3
count = np.sum(a % 3 == 0)

                                                                    # Create array of elements divisible by 3
div_by_3 = a[a % 3 == 0]                                            # Added this line to define div_by_3

print("Array is:\n", a)
print("Elements divisible by 3:\n", div_by_3)
print("Number of elements divisible by 3:", count)                  #added a feature that can sum all of the numbers  divisible by 3 

Array is:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
Number of elements divisible by 3: 33
